# Generated by Django 4.1 on 2022-09-05 21:48

import datetime
from django.db import migrations, models
from datetime import date


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='fecha',
            field=models.DateField(default=date.today),
        ),
    ]
