# Generated by Django 4.1 on 2022-09-15 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0005_alter_contactenos_mensaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
